#==============================================================
# Debug mode
#==============================================================
localhost: https://localhost:3000
debug : false


#==============================================================
# Maintain mode
#==============================================================
maintain : false


#==============================================================
# Administator info
#==============================================================
admin_name: 網站管理員
admin_email: hello@kobeengineer.io


#==============================================================
# Site settings
#==============================================================
site_name         : 靠北工程師 KOBEENGINEER
site_title        : 靠北工程師
site_description  : KOBEENGINEER
site_keywords     : 工程師,碼農,肝,乖乖,女友
site_url          : https://kobeengineer.io
og_type           : website
og_image          : https://kobeengineer.io/images/fb/default.jpg
ga_track_id       : UA-56488643-8


#==============================================================
# Facebook APP
#==============================================================
fb_app_id: 1070489439641754
fb_app_version: v2.5


#==============================================================
# Submition form
#==============================================================
license:
  - 0.當你勾選後，即代表您同意遵守 Facebook 社群使用規則.
  - 1.嚴禁發表任何霸凌內容、或有相關意圖之內容，違反將被刪除
  - 2.靠北勿指名道姓、透漏任何個資或隱私資訊，或在文中直接提到任何公司、機構、學校名稱，違反者一律刪文
  - 3.嚴禁發表任何情色、暴力之相關內容，或有相關意圖之內容，違反將被刪除
  - 4.與本版主題無關、或發文內容明顯為測試意圖、或無關之推薦文、廣告文、職缺文，將被刪除
  - 5.轉載他人原創發文時，一律需經過原作者同意並註明出處
  - 6.因應臉書政策，涉及種族歧視之發文格殺勿論
  - 7.請善用「███」取代敏感字詞
privacy_policy: 非常歡迎您光臨 kobeengineer.io (以下簡稱本網站)，為了讓您能夠安心的使用本網站的各項服務與資訊，特此向您說明本網站的隱私權保護政策，以保障您的權益，請您詳閱下列內容： 一、隱私權保護政策的適用範圍 隱私權保護政策內容，包括本網站如何處理在您使用網站服務時收集到的個人識別資料。隱私權保護政策不適用於本網站以外的相關連結網站，也不適用於非本網站所委託或參與管理的人員。 二、資料的蒐集與使用方式 為了在本網站上提供您最佳的互動性服務，可能會請您提供相關個人的資料，其範圍如下：於使用發文服務時，伺服器會自行記錄相關行徑，包括您使用連線設備的去識別性的IP位址、使用時間，做為我們增進網站服務的參考依據。於使用檢舉系統時，伺服器會自行記錄相關行徑，包括您提交檢舉時使用之臉書帳號ID、檢舉時間，做為系統自動判斷發文下架之依據。以上之記錄皆為內部應用，決不對外公布。除非取得您的同意或其他法令之特別規定，本網站絕不會將您的個人資料揭露予第三人或使用於蒐集目的以外之其他用途。 三、資料之保護 本網站主機均設有防火牆、防毒系統等相關的各項資訊安全設備及必要的安全防護措施，加以保護網站及您的個人資料採用嚴格的保護措施。 四、網站對外的相關連結 本網站的網頁提供其他網站的網路連結，您也可經由本網站所提供的連結，點選進入其他網站。但該連結網站不適用本網站的隱私權保護政策，您必須參考該連結網站中的隱私權保護政策。 五、隱私權保護政策之修正 本網站隱私權保護政策將因應需求隨時進行修正，修正後的條款將刊登於網站上。


#==============================================================
# Build exclude
#==============================================================
exclude:
  - gulpfile.js
  - package.json
  - node_modules
  - assets
  - yarn.lock


#==============================================================
# Html compress config
#==============================================================
compress_html:
  clippings: all

